# ==================== APPLICATION ====================
spring.application.name=user-service
server.port=8081

# ==================== EXTERNAL CONFIG ====================
spring.config.import=file:C:/Users/salih/Desktop/hatirlabeni-app/backend/config/application.properties

# ==================== DATABASE ====================
spring.datasource.url=${USER_DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update

# ==================== JWT ====================
jwt.secret=${SECRET_KEY}
jwt.expiration=${EXPIRATION}

# ==================== MICROSERVICES ====================
auth_service.url=${auth_service_url}

# ==================== SPRING BOOT ====================
spring.main.banner-mode=off