spring.application.name=user-service
server.port=8081

spring.config.import=file:C:/Users/salih/Desktop/hatirlabeni-app/backend/config/application.properties

spring.datasource.url=${USER_DB_URL}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.username=${DB_USERNAME}

jwt.secret=${SECRET_KEY}
jwt.expiration=${EXPIRATION}

auth_service.url=${auth_service_url}

spring.main.banner-mode=off
spring.jpa.hibernate.ddl-auto=update