# ==================== APPLICATION ====================
spring.application.name=authentication-service
server.port=8082

# ==================== EXTERNAL CONFIG ====================
spring.config.import=file:C:/Users/salih/Desktop/hatirlabeni-app/backend/config/application.properties

# ==================== DATABASE ====================
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${AUTH_DB_URL}

# ==================== ROOT USER ====================
app.root.email=${ROOT_EMAIL}
app.root.password=${ROOT_PASSWORD}
app.root.username=${ROOT_USERNAME}

# ==================== JWT ====================
jwt.secret=${SECRET_KEY}
jwt.expiration=${EXPIRATION}
REFRESH_EXPIRATION=${REFRESH_EXPIRATION}

# ==================== MICROSERVICES ====================
user-service.url=${user-service.url}

# ==================== EMAIL ====================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# ==================== FRONTEND & COOKIE ====================
FRONTEND_URL=http://localhost:5173
COOKIE_SECURE=${COOKIE_SECURE}

# ==================== GOOGLE OAUTH2 ====================
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email

# ==================== SPRING BOOT ====================
spring.main.banner-mode=off