# ==================== APPLICATION ====================
spring.application.name=product-service
server.port=8083

# ==================== EXTERNAL CONFIG ====================
spring.config.import=optional:file:/config/application.properties,optional:file:C:/Users/salih/Desktop/hatirlabeni-app/backend/config/application.properties

# ==================== DATABASE ====================
spring.jpa.hibernate.ddl-auto=update

spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=${PRODUCT_DB_URL}

# ==================== SPRING BOOT ====================
spring.main.banner-mode=off