spring.application.name=api-gateway
server.port=8080

# User Service
spring.cloud.gateway.server.webmvc.routes[0].id=user-service
spring.cloud.gateway.server.webmvc.routes[0].uri=http://localhost:8081
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/api/v1/users/**

# Authentication Service
spring.cloud.gateway.server.webmvc.routes[1].id=authentication-service
spring.cloud.gateway.server.webmvc.routes[1].uri=http://localhost:8082
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/api/v1/auth/**

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=when_authorized
management.info.env.enabled=true
